name: Love actions for macOS AppStore
description: macOS AppStore CI/CD for LÖVE based games
branding:
  icon: "heart"
  color: "yellow"
inputs:
  app-name:
    description: |
      App display name
      Would be used in platform/xcode/macosx/love-macosx.plist
    required: false
    default: "LÖVE for macOS"
  bundle-id:
    description: |
      App bundle id
      Would be used in platform/xcode/love.xcodeproj/project.pbxproj
    required: false
    default: "org.love2d.macOS"
  copyright:
    description: |
      App copyright info
      Would be used in platform/xcode/macosx/love-macosx.plist
    required: false
  icon-path:
    description: |
      Icon path
      Should be .icns format
      Would be used in platform/xcode/Images.xcassets/OS X AppIcon.appiconset
    required: true
    default: "./icon.icns"
  love-package:
    description: |
      Love package
      Would be used to assemble the executable
    required: false
    default: "./game.love"
  product-name:
    description: |
      Base name of the package
      Would be used to rename products
    required: false
    default: "love_app"
  version-string:
    description: |
      App version string
      Use 3 numbers seperated by dots
      Looks like 3.2.1
    required: false
    default: "11.4"
  output-folder:
    description: |
      Packages output folder
      All packages would be placed here
    required: false
    default: "./build"
  apple-distribution-base64:
    description: |
      Apple Distribution certificate base64 content
      Would be used to sign the app
    required: true
  apple-distribution-password:
    description: |
      Apple Distribution certificate password
      Would be used to sign the app
    required: true
  mac-installer-base64:
    description: |
      Mac Installer Distribution certificate base64 content
      Would be used to sign the app
    required: true
  mac-installer-password:
    description: |
      Mac Installer Distribution certificate password
      Would be used to sign the app
    required: true
  provision-profile-base64:
    description: |
      App Store type of macos Provisioning Profile's base64 content
      Would be used to sign the app
    required: true
  account-username:
    description: |
      Account username
      Would be used to validate and upload the package
    required: true
  account-password:
    description: |
      Account password
      Would be used to validate and upload the package
    required: true
  team-id:
    description: |
      Developer team id
      Would be used to upload the package
    required: true
  apple-id:
    description: |
      App Apple ID
      Would be used to upload the package
    required: true
outputs:
  package-paths:
    description: |
      Paths to the built packages in a bash list
      Would be paths relative to repository root, separated by spaces
      Looks like: ./build/game.apk ./build/game.abb
    value: ${{ steps.gather-packages.outputs.package-paths }}
runs:
  using: "composite"
  steps:
    - name: Create directories
      shell: bash
      run: |
        mkdir -p ./love-actions-macos-appstore/
        mkdir -p ${{ inputs.output-folder }}
    - name: Setup environment
      id: setup-env
      shell: python3 {0}
      run: |
        import os
        version_string = "${{ inputs.version-string }}"
        version_segments = version_string.split(".")
        build_version = version_segments[0] + version_segments[1].zfill(2) + version_segments[2].zfill(2)
        attempt = "${{ github.run_attempt }}"
        os.system("echo ::set-output name=bundle-version::" + build_version + ".2.${{ github.run_number }}" + attempt.zfill(2))
    - name: Checkout love
      uses: actions/checkout@v3
      with:
        path: ./love-actions-macos-appstore/love
        ref: c35356c841976eb6f370347b81eec845d5520338
        repository: love2d/love
    - name: Checkout framework SDK
      uses: actions/checkout@v3
      with:
        path: ./love-actions-macos-appstore/love-apple-dependencies
        ref: 402eed62c2bd654a860bb64544393285fb640497
        repository: love2d/love-apple-dependencies
    - name: Move framework SDK and love package
      shell: bash
      run: |
        mv ./love-actions-macos-appstore/love-apple-dependencies/macOS/Frameworks/ ./love-actions-macos-appstore/love/platform/xcode/macosx
        mv ${{ inputs.love-package }} ./love-actions-macos-appstore/love/platform/xcode/game.love
        mkdir -p ./love-actions-macos-appstore/love/platform/xcode/build/Debug
        mkdir -p ./love-actions-macos-appstore/love/platform/xcode/build/Release
    - name: Process icons
      shell: bash
      run: |
        rm -rf ./love-actions-macos-appstore/love/platform/xcode/Images.xcassets/OS\ X\ AppIcon.appiconset/*.png
        iconutil -c iconset -o ./love-actions-macos-appstore/icon.iconset ${{ inputs.icon-path }}
        mv -f ./love-actions-macos-appstore/icon.iconset/* ./love-actions-macos-appstore/love/platform/xcode/Images.xcassets/OS\ X\ AppIcon.appiconset/
    - name: Create keychain and import certificates, provision profiles
      env:
        CERTIFICATE_PATH: ./love-actions-macos-appstore/cert.p12
        KEYCHAIN_PATH: ./love-actions-macos-appstore/build.keychain
        KEYCHAIN_PASSWORD: build_keychain_password
        PROVISION_PROFILE_PATH: ./love-actions-macos-appstore/macos_appstore.provisionprofile
      shell: bash
      run: |
        security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security default-keychain -s $KEYCHAIN_PATH
        security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
        
        echo -n "${{ inputs.apple-distribution-base64 }}" | base64 --decode --output $CERTIFICATE_PATH
        security import $CERTIFICATE_PATH -A -f pkcs12 -k $KEYCHAIN_PATH -P "${{ inputs.apple-distribution-password }}" -t cert
        rm $CERTIFICATE_PATH
        
        echo -n "${{ inputs.mac-installer-base64 }}" | base64 --decode --output $CERTIFICATE_PATH
        security import $CERTIFICATE_PATH -A -f pkcs12 -k $KEYCHAIN_PATH -P "${{ inputs.mac-installer-password }}" -t cert
        rm $CERTIFICATE_PATH
        
        security set-key-partition-list -S apple-tool:,apple:,codesign:,productbuild:,productsign: -s -k $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
        
        echo -n "${{ inputs.APPLE_PP_DEVELOPER_ID_APPLICATION }}" | base64 --decode --output $PROVISION_PROFILE_PATH
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PROVISION_PROFILE_PATH ~/Library/MobileDevice/Provisioning\ Profiles
    - name: Modify XCode project
      shell: bash
      run: |
        npm i plist xcode

        cat <<EOT >> temp.js
        const fs = require('fs');
        const plist = require('plist');
        const xcode = require('xcode');

        const provisioningProfile = fs.readFileSync('./love-actions-macos-appstore/macos_appstore.provisionprofile', 'utf8');
        const uuid = provisioningProfile.substr(provisioningProfile.indexOf('>', provisioningProfile.indexOf('UUID') + 10) + 1, 36);

        console.log(uuid);

        const configuration = 'Release'

        const liblovePbxprojPath = './love-actions-macos-appstore/love/platform/xcode/liblove.xcodeproj/project.pbxproj';
        const libloveProject = xcode.project(liblovePbxprojPath).parseSync();
        const libloveTarget = 'liblove-macosx'
        libloveProject.updateBuildProperty('MACOSX_DEPLOYMENT_TARGET', '10.9', configuration, libloveTarget);
        fs.writeFileSync(liblovePbxprojPath, libloveProject.writeSync());

        const lovePbxprojPath = './love-actions-macos-appstore/love/platform/xcode/love.xcodeproj/project.pbxproj';
        const loveProject = xcode.project(lovePbxprojPath).parseSync();
        const loveTarget = 'love-macosx'
        loveProject.updateBuildProperty('CODE_SIGN_IDENTITY', '"Apple Distribution"', configuration, loveTarget);
        loveProject.updateBuildProperty('DEVELOPMENT_TEAM', '${{ inputs.team-id }}', configuration, loveTarget);
        loveProject.updateBuildProperty('MACOSX_DEPLOYMENT_TARGET', '10.9', configuration, loveTarget);
        loveProject.updateBuildProperty('MARKETING_VERSION', '${{ inputs.version-string }}', configuration, loveTarget);
        loveProject.updateBuildProperty('PRODUCT_BUNDLE_IDENTIFIER', '${{ inputs.bundle-id }}', configuration, loveTarget);
        loveProject.updateBuildProperty('PRODUCT_NAME', '${{ inputs.product-name }}', configuration, loveTarget);
        loveProject.addResourceFile(
            './game.love',
            {target: loveProject.findTargetKey('"love-macosx"')},
            loveProject.findPBXGroupKey({name: 'Resources'})
        );
        fs.writeFileSync(lovePbxprojPath, loveProject.writeSync());

        const infoPath = './love-actions-macos-appstore/love/platform/xcode/macosx/love-macosx.plist';
        const infoPlist = plist['parse'](fs.readFileSync(infoPath, 'utf8'));
        infoPlist['CFBundleExecutable'] = '${{ inputs.product-name }}';
        infoPlist['CFBundleName'] = '${{ inputs.app-name }}';
        infoPlist['CFBundleVersion'] = '${{ steps.setup-env.outputs.bundle-version }}';
        infoPlist['NSHumanReadableCopyright'] = '${{ inputs.copyright }}';
        delete infoPlist['CFBundleDocumentTypes'];
        delete infoPlist['UTExportedTypeDeclarations'];
        fs.writeFileSync(infoPath, plist['build'](infoPlist));

        const entitlementsPath = './love-actions-macos-appstore/love/platform/xcode/love.entitlements';
        const entitlementsPlist = plist['parse'](fs.readFileSync(entitlementsPath, 'utf8'));
        entitlementsPlist['com.apple.security.app-sandbox'] = true;
        fs.writeFileSync(entitlementsPath, plist['build'](entitlementsPlist));

        const freetypeInfoPath = './love-actions-macos-appstore/love/platform/xcode/macosx/Frameworks/freetype.framework/Resources/Info.plist';
        const freetypeInfoPlist = plist['parse'](fs.readFileSync(freetypeInfoPath, 'utf8'));
        freetypeInfoPlist['CFBundleIdentifier'] = 'org.freetype.freetype';
        fs.writeFileSync(freetypeInfoPath, plist['build'](freetypeInfoPlist));
        
        const exportPlistPath = './love-actions-macos-appstore/love/platform/xcode/macosx/macos-copy-app.plist';
        const exportPlist = plist['parse'](fs.readFileSync(exportPlistPath, 'utf8'));
        exportPlist['method'] = 'app-store';
        exportPlist['signingCertificate'] = 'Apple Distribution';
        exportPlist['installerSigningCertificate'] = '3rd Party Mac Developer Installer';
        exportPlist['teamID'] = '${{ inputs.team-id }}';
        exportPlist['provisioningProfiles'] = {'${{ inputs.bundle-id }}': uuid};
        fs.writeFileSync(exportPlistPath, plist['build'](exportPlist));

        const iconPath = './love-actions-macos-appstore/love/platform/xcode/Images.xcassets/OS X AppIcon.appiconset/Contents.json';
        const iconContents = JSON.parse(fs.readFileSync(iconPath, 'utf8'));
        iconContents.images.forEach(image => {
            image.filename = 'icon_' + image.size + (image.scale === '2x' ? '@2x' : '') + '.png';
        });
        fs.writeFileSync(iconPath, JSON.stringify(iconContents));

        console.info('Project info updated.');
        EOT

        node temp.js
    - name: Build MacOS app
      env:
        ARCHIVE_PATH: ./love-actions-macos-appstore/archive.xcarchive
        KEYCHAIN_PATH: ./love-actions-macos-appstore/build.keychain
        KEYCHAIN_PASSWORD: build_keychain_password
      shell: bash
      run: |
        security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH

        xcodebuild clean archive -quiet \
        -project ./love-actions-macos-appstore/love/platform/xcode/love.xcodeproj \
        -scheme love-macosx \
        -configuration Release \
        -archivePath ${{ env.ARCHIVE_PATH }} \
        OTHER_CFLAGS="-Wno-everything" \
        OTHER_CODE_SIGN_FLAGS="--deep --force --generate-entitlement-der --strict --timestamp --options runtime"

        xcodebuild -exportArchive \
        -archivePath ${{ env.ARCHIVE_PATH }} \
        -exportPath ./love-actions-macos-appstore/ \
        -exportOptionsPlist ./love-actions-macos-appstore/love/platform/xcode/macosx/macos-copy-app.plist

        ls -l ./love-actions-macos-appstore/
    - name: Validate installer pkg
      shell: bash
      run: |
        xcrun altool --validate-app -t macos \
        -u "${{ inputs.account-username }}" -p "${{ inputs.account-password }}" \
        -f "./love-actions-macos-appstore/${{ inputs.app-name }}.pkg"
    - name: Upload package
      shell: bash
      run: |
        xcrun altool --upload-package "./love-actions-macos-appstore/${{ inputs.app-name }}.pkg" -t "macos" --apple-id "${{ inputs.apple-id }}" \
        -u "${{ inputs.account-username }}" -p "${{ inputs.account-password }}" --team-id "${{ inputs.team-id }}" \
        --bundle-version "${{ steps.setup-env.outputs.bundle-version }}" --bundle-short-version-string "${{ inputs.version-string }}" --bundle-id "${{ inputs.bundle-id }}"
    - name: Move installer pkg
      shell: bash
      run: |
        mv "./love-actions-macos-appstore/${{ inputs.app-name }}.pkg" "${{ inputs.output-folder }}/${{ inputs.product-name }}.pkg"
    - name: Gather packages in output folder
      id: gather-packages
      shell: bash
      run: |
        echo ::set-output name=package-paths::$(ls -d ${{ inputs.output-folder }}/*)
    - name: Cleanup
      shell: bash
      run: |
        rm -rf ./love-actions-macos-appstore/
